apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: job-creator-role
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/tracking-id: {{ .Values.argocdTrackingId }}
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["batch"]
    resources: ["jobs","jobs/status"]
    verbs: ["create", "list", "delete", "get", "watch"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["create", "list", "get", "delete", "patch"]
  - apiGroups: [""]
    resources: ["endpoints"]
    verbs: ["list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: job-creator-rolebinding
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/tracking-id: {{ .Values.argocdTrackingId }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: job-creator-role
subjects:
  - kind: ServiceAccount
    name: job-creator
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: job-creator
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/tracking-id: {{ .Values.argocdTrackingId }}
